development:
  sessions:
    default:
      database: rails_with_mongodb_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: rails_with_mongodb_test
      hosts:
        - localhost:27017
